params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: False
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name:  'None'

  config:
    name: 3m_cv
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.001
    truncate_grads: True
    env_name: smac
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 128
    minibatch_size: 1536 # 3 * 512
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    kl_threshold: 0.05
    normalize_input: True
    normalize_value: False
    use_action_masks: True

    env_config:
      name: 3m
      frames: 1
      transpose: False
      central_value: True
      reward_only_positive: True
      state_last_action: True

    central_value_config:
      minibatch_size: 512
      mini_epochs: 4
      learning_rate: 5e-4
      clip_value: False
      normalize_input: True
      network:
        name: actor_critic
        central_value: True
        joint_obs_actions:
            embedding: False
            embedding_scale: 1 #(actions // embedding_scale)
            mlp_scale: 4 # (mlp from obs size) // mlp_out_scale
        mlp:
          units: [256, 128]
          activation: relu
          initializer:
            #name: default
            name: default
            scale: 2 
          regularizer:
            name:  'None'