params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c_lstm

  network:
    name: actor_critic
    separate: True
    space: 
      discrete:
      
    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name: 'None'
    lstm:
      units: 128
      concated: False
  config:
    name: sc2_fc
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name: smac
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 64
    minibatch_size: 1536
    mini_epochs: 8
    critic_coef: 1
    lr_schedule:  None
    kl_threshold: 0.05
    normalize_input: False
    seq_length: 4
    use_action_masks: True

    env_config:
      name: 3s_vs_4z
      frames: 1
      random_invalid_step: False