params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    #normalization: layer_norm
    space: 
      discrete:

    mlp:
      units: [256, 128]
      activation: relu
      initializer:
        name: default 
      regularizer:
        name: None
  config:
    name: 8m
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    score_to_win: 20
    grad_norm: 0.5
    entropy_coef: 0.001
    truncate_grads: True
    env_name: smac
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    horizon_length: 128
    minibatch_size: 4096
    mini_epochs: 4
    critic_coef: 1
    lr_schedule: None
    kl_threshold: 0.05
    normalize_input: True
    seq_length: 2
    use_action_masks: True
    ignore_dead_batches : False
    max_epochs: 10000
    env_config:
      name: 8m
      frames: 1
      transpose: False
      random_invalid_step: False